"""Add Knowledge Card fields to RAGDocument

Revision ID: d9ca94d58e30
Revises: 8415375715be
Create Date: 2026-07-30 18:41:28.760058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd9ca94d58e30'
down_revision: Union[str, None] = '8415375715be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rag_documents', sa.Column('card_id', sa.UUID(), nullable=True))
    op.add_column('rag_documents', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.add_column('rag_documents', sa.Column('type', sa.String(length=50), nullable=True))
    op.add_column('rag_documents', sa.Column('card_status', sa.String(length=50), nullable=True))
    op.add_column('rag_documents', sa.Column('version', sa.Integer(), nullable=True))
    op.add_column('rag_documents', sa.Column('project', sa.String(length=100), nullable=True))
    op.add_column('rag_documents', sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('rag_documents', sa.Column('confidence', sa.String(length=50), nullable=True))
    op.add_column('rag_documents', sa.Column('owner', sa.String(length=255), nullable=True))
    op.add_column('rag_documents', sa.Column('source_pointer', sa.Text(), nullable=True))
    op.add_column('rag_documents', sa.Column('source_checksum', sa.String(length=255), nullable=True))
    op.add_column('rag_documents', sa.Column('source_created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('rag_documents', sa.Column('document_id', sa.UUID(), nullable=True))
    op.add_column('rag_documents', sa.Column('next_review_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('rag_documents', sa.Column('is_chunk', sa.Boolean(), nullable=True))
    op.add_column('rag_documents', sa.Column('parent_card_id', sa.UUID(), nullable=True))
    op.add_column('rag_documents', sa.Column('chunk_index', sa.Integer(), nullable=True))
    op.create_index(op.f('rag_documents_card_id_idx'), 'rag_documents', ['card_id'], unique=True)
    op.create_index(op.f('rag_documents_card_status_idx'), 'rag_documents', ['card_status'], unique=False)
    op.create_index(op.f('rag_documents_confidence_idx'), 'rag_documents', ['confidence'], unique=False)
    op.create_index(op.f('rag_documents_document_id_idx'), 'rag_documents', ['document_id'], unique=False)
    op.create_index(op.f('rag_documents_owner_idx'), 'rag_documents', ['owner'], unique=False)
    op.create_index(op.f('rag_documents_parent_card_id_idx'), 'rag_documents', ['parent_card_id'], unique=False)
    op.create_index(op.f('rag_documents_project_idx'), 'rag_documents', ['project'], unique=False)
    op.create_index(op.f('rag_documents_tenant_id_idx'), 'rag_documents', ['tenant_id'], unique=False)
    op.create_index(op.f('rag_documents_type_idx'), 'rag_documents', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('rag_documents_type_idx'), table_name='rag_documents')
    op.drop_index(op.f('rag_documents_tenant_id_idx'), table_name='rag_documents')
    op.drop_index(op.f('rag_documents_project_idx'), table_name='rag_documents')
    op.drop_index(op.f('rag_documents_parent_card_id_idx'), table_name='rag_documents')
    op.drop_index(op.f('rag_documents_owner_idx'), table_name='rag_documents')
    op.drop_index(op.f('rag_documents_document_id_idx'), table_name='rag_documents')
    op.drop_index(op.f('rag_documents_confidence_idx'), table_name='rag_documents')
    op.drop_index(op.f('rag_documents_card_status_idx'), table_name='rag_documents')
    op.drop_index(op.f('rag_documents_card_id_idx'), table_name='rag_documents')
    op.drop_column('rag_documents', 'chunk_index')
    op.drop_column('rag_documents', 'parent_card_id')
    op.drop_column('rag_documents', 'is_chunk')
    op.drop_column('rag_documents', 'next_review_at')
    op.drop_column('rag_documents', 'document_id')
    op.drop_column('rag_documents', 'source_created_at')
    op.drop_column('rag_documents', 'source_checksum')
    op.drop_column('rag_documents', 'source_pointer')
    op.drop_column('rag_documents', 'owner')
    op.drop_column('rag_documents', 'confidence')
    op.drop_column('rag_documents', 'tags')
    op.drop_column('rag_documents', 'project')
    op.drop_column('rag_documents', 'version')
    op.drop_column('rag_documents', 'card_status')
    op.drop_column('rag_documents', 'type')
    op.drop_column('rag_documents', 'tenant_id')
    op.drop_column('rag_documents', 'card_id')
    # ### end Alembic commands ###
